name: Check Health of UT

# Every 12 minutes except for 23:00-4:59
# */12 0-3,5-23 * * *

on:
  schedule:
    - cron: '*/12 5-22 * * *'

jobs:
  check_health_ut:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://ultratheorie.nl/ping"
        expected-statuses: "200,301,302"
