name: Check Health of UT

on:
  push:
    branches: [ master ]

jobs:
  check_health_ut:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://ultratheorie.nl/administratie"
        expected-statuses: "200,301,302"